/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.park.GUI;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

import com.park.control.CustomerControl;
import com.park.control.SpaceControl;
import com.park.model.Customer;
import com.park.model.Space;
import com.park.service.MainGUIService;

import java.awt.event.MouseAdapter;

import javax.swing.JMenuItem;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;
import java.awt.GridLayout;
import java.awt.Component;

import javax.swing.UIManager;
import javax.swing.ImageIcon;

/**
 *
 * @author Peter
 */
public class MainGUI extends javax.swing.JFrame implements MouseListener{
     public ArrayList<JButton> BSButtons = new ArrayList<JButton>();
     public ArrayList<JButton> BDButtons = new ArrayList<JButton>();
     
     public MainGUIService mainGUIService = new MainGUIService(this);
     public String user;
 	 private Thread thread;
 	 public JLabel timeLabel;
 	 public JLabel occupiedLabel;
 	 public JLabel reservedLabel;
 	 public JLabel emptyLabel;
 	 public JLabel rateLabel;
 	 public JTable selectedCustomerGoods;
 	 public MainGUI main = this;
 	 public Space selectedSpace;
 	 public Customer selectedCustomer;
 	 public String selectedButtonText;
 	 public ArrayList<JLabel> roomInfos=new ArrayList<JLabel>();
 	 public ArrayList<JLabel> customerInfos = new ArrayList<JLabel>();
  


    /**
     * Creates new form BookingSystem
     */
    public MainGUI(String user) {
    	this.user = user;
    	getContentPane().setBackground(Color.WHITE);
    	setResizable(false);
        initComponents();
        mainGUIService.refreshSpaceButtons();
    	selectedSpace=null;
	 	selectedCustomer=null;
	 	selectedButtonText="";

        thread=new Thread()
		{
			
			public void run()
			{		
				SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
				while(true)
				{
					try {
						Thread.sleep(1000);
					} catch (InterruptedException e) {
						
						e.printStackTrace();
					}
				}
			}
		};
		thread.start();
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jButton1.setIcon(new ImageIcon(MainGUI.class.getResource("/com/park/image/05.png")));
        jButton1.setFont(new Font("幼圆", Font.BOLD, 31));
        jButton1.setContentAreaFilled(false);
        jButton3 = new javax.swing.JButton();
        jButton3.setIcon(new ImageIcon(MainGUI.class.getResource("/com/park/image/05.png")));
        jButton3.setFont(new Font("幼圆", Font.BOLD, 30));
        jButton3.setForeground(UIManager.getColor("Button.focus"));
        jButton3.setContentAreaFilled(false);
        jButton4 = new javax.swing.JButton();
        jButton4.setIcon(new ImageIcon(MainGUI.class.getResource("/com/park/image/05.png")));
        jButton4.setFont(new Font("幼圆", Font.BOLD, 31));
        jButton4.setContentAreaFilled(false);
        jMenuBar1 = new javax.swing.JMenuBar();
   

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("停车位系统");

        jTabbedPane2.setFont(new java.awt.Font("新宋体", 1, 12));
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(Color.WHITE);
        
                jTabbedPane2.addTab("贵宾停车位", jPanel1);
                
                BSButton1 = new JButton("BS101");             
                jPanel1.setLayout(new GridLayout(0, 9, 0, 0));
                BSButton1.setContentAreaFilled(false);
                BSButton1.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton1.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton1);
                BSButtons.add(BSButton1);
                
                BSButton2 = new JButton("BS102");
                BSButton2.setContentAreaFilled(false);
                BSButton2.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton2.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton2);
                BSButtons.add(BSButton2);
                
                BSButton3 = new JButton("BS103");
                BSButton3.setContentAreaFilled(false);
                BSButton3.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton3.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton3);
                BSButtons.add(BSButton3);
                
                BSButton4 = new JButton("BS104");
                BSButton4.setContentAreaFilled(false);
                BSButton4.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton4.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton4);
                BSButtons.add(BSButton4);
                
                BSButton5 = new JButton("BS105");
                BSButton5.setContentAreaFilled(false);
                BSButton5.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton5.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton5);
                BSButtons.add(BSButton5);
                
                BSButton6 = new JButton("BS106");
                BSButton6.setContentAreaFilled(false);
                BSButton6.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton6.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton6);
                BSButtons.add(BSButton6);
                
                BSButton7 = new JButton("BS107");
                BSButton7.setContentAreaFilled(false);
                BSButton7.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton7.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton7);
                BSButtons.add(BSButton7);
                
                BSButton8 = new JButton("BS108");
                BSButton8.setContentAreaFilled(false);
                BSButton8.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton8.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton8);
                BSButtons.add(BSButton8);
                
                BSButton9 = new JButton("BS109");
                BSButton9.setContentAreaFilled(false);
                BSButton9.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton9.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton9);
                BSButtons.add(BSButton9);
                
                BSButton10 = new JButton("BS110");
                BSButton10.setContentAreaFilled(false);
                BSButton10.setVerticalTextPosition(SwingConstants.BOTTOM);
                BSButton10.setHorizontalTextPosition(SwingConstants.CENTER);
                jPanel1.add(BSButton10);
                BSButtons.add(BSButton10);
                
                label = new JLabel("");
                jPanel1.add(label);
                
                label_2 = new JLabel("");
                jPanel1.add(label_2);
                
                label_3 = new JLabel("");
                jPanel1.add(label_3);
                
                label_4 = new JLabel("");
                jPanel1.add(label_4);
                
                label_5 = new JLabel("");
                jPanel1.add(label_5);
                
                label_6 = new JLabel("");
                jPanel1.add(label_6);
                
                label_7 = new JLabel("");
                jPanel1.add(label_7);
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(Color.WHITE);
        
        BDButton1 = new JButton("BD201");
        BDButton1.setContentAreaFilled(false);
        BDButton1.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton1.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton2 = new JButton("BD202");
        BDButton2.setContentAreaFilled(false);
        BDButton2.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton2.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton3 = new JButton("BD203");
        BDButton3.setContentAreaFilled(false);
        BDButton3.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton3.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton5 = new JButton("BD205");
        BDButton5.setContentAreaFilled(false);
        BDButton5.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton5.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton4 = new JButton("BD204");
        BDButton4.setContentAreaFilled(false);
        BDButton4.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton4.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton6 = new JButton("BD206");
        BDButton6.setContentAreaFilled(false);
        BDButton6.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton6.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton7 = new JButton("BD207");
        BDButton7.setContentAreaFilled(false);
        BDButton7.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton7.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton8 = new JButton("BD208");
        BDButton8.setContentAreaFilled(false);
        BDButton8.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton8.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton9 = new JButton("BD209");
        BDButton9.setContentAreaFilled(false);
        BDButton9.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton9.setHorizontalTextPosition(SwingConstants.CENTER);
        
        BDButton10 = new JButton("BD210");
        BDButton10.setContentAreaFilled(false);
        BDButton10.setVerticalTextPosition(SwingConstants.BOTTOM);
        BDButton10.setHorizontalTextPosition(SwingConstants.CENTER);
        BDButtons.add(BDButton1);
        BDButtons.add(BDButton2);
        BDButtons.add(BDButton3);
        BDButtons.add(BDButton4);
        BDButtons.add(BDButton5);
        BDButtons.add(BDButton6);
        BDButtons.add(BDButton7);
        BDButtons.add(BDButton8);
        BDButtons.add(BDButton9);
        BDButtons.add(BDButton10);
                
                        jTabbedPane2.addTab("普通停车位", jPanel2);
                        jPanel2.setLayout(new GridLayout(0, 9, 0, 0));
                        jPanel2.add(BDButton1);
                        jPanel2.add(BDButton2);
                        jPanel2.add(BDButton3);
                        jPanel2.add(BDButton4);
                        jPanel2.add(BDButton5);
                        jPanel2.add(BDButton6);
                        jPanel2.add(BDButton7);
                        jPanel2.add(BDButton8);
                        jPanel2.add(BDButton9);
                        jPanel2.add(BDButton10);
                        
                        label_8 = new JLabel("");
                        jPanel2.add(label_8);
                        
                        label_9 = new JLabel("");
                        jPanel2.add(label_9);
                        
                        label_10 = new JLabel("");
                        jPanel2.add(label_10);
                        
                        label_11 = new JLabel("");
                        jPanel2.add(label_11);
                        
                        label_12 = new JLabel("");
                        jPanel2.add(label_12);
                        
                        label_13 = new JLabel("");
                        jPanel2.add(label_13);
                        
                        label_14 = new JLabel("");
                        jPanel2.add(label_14);

        jButton1.setBackground(new Color(102, 204, 204));
        jButton1.setText("停车");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(Color.CYAN);
        jButton3.setText("抢车位");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(Color.RED);
        jButton4.setText("付钱");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton3)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
        			.addGap(98)
        			.addComponent(jTabbedPane2, GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        			.addGap(246))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(39, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
        					.addGap(33)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
        					.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        					.addGap(2))
        				.addComponent(jTabbedPane2, GroupLayout.PREFERRED_SIZE, 372, GroupLayout.PREFERRED_SIZE))
        			.addGap(560))
        );
        layout.linkSize(SwingConstants.VERTICAL, new Component[] {jButton1, jButton3, jButton4});
        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jButton1, jButton3, jButton4});
        getContentPane().setLayout(layout);
       
        for(int i = 0;i<BSButtons.size();i++)             //每个按钮都添加一个点击事件
        {   
        	BSButtons.get(i).addMouseListener(main);
        }
        for(int i = 0;i<BDButtons.size();i++)
        {  
            BDButtons.get(i).addMouseListener(main);
        }
 
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:      //checkin
    	if(selectedSpace==null)
    	{
    		JOptionPane.showConfirmDialog(null, "请选择你的车位！","提示:", JOptionPane.CLOSED_OPTION);
		    return;
    	}
    	if(selectedSpace.getSpaceState().equals("已占用"))
    	{
    		JOptionPane.showConfirmDialog(null, "此车位已占用","提示:", JOptionPane.CLOSED_OPTION);
		    return;
    	}
    	if(selectedSpace.getSpaceState().equals("已预约"))
    	{
    		ResToSpace res = new ResToSpace(selectedSpace,main);
    		res.setVisible(true);
    	}
    	if(selectedSpace.getSpaceState().equals("可用"))
    	{
    		 CheckIn checkin = new CheckIn(selectedSpace,main);
    	     checkin.setVisible(true);
    	}
    	else
    	{
    		JOptionPane.showConfirmDialog(null, "请选择你的车位！","提示:", JOptionPane.CLOSED_OPTION);
		    return;
    		
    	}
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    	if(selectedSpace==null) //抢车位
    	{
    		JOptionPane.showConfirmDialog(null, "亲~请选择","提示:", JOptionPane.CLOSED_OPTION);	
        	
        }
    	else if(selectedSpace.getSpaceState().equals("已占用")) 	 	
    	{
			JOptionPane.showConfirmDialog(null, "亲~已经占用了","提示:", JOptionPane.CLOSED_OPTION);	
    	}
    	else if(selectedSpace.getSpaceState().equals("已预约")) 	 	
    	{		
			JOptionPane.showConfirmDialog(null, "亲~已经被定了","提示:", JOptionPane.CLOSED_OPTION);		
    	}
    	else if(selectedSpace.getSpaceState().equals("可用"))
    	{
    		AddReservation addReservation = new AddReservation(selectedSpace,main);
    		addReservation.setVisible(true);
    	}
        // TODO add your handling code here:
    	
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    	
    	if(selectedSpace==null)
    	{
    		JOptionPane.showConfirmDialog(null, "请选择自己的车位","提示:", JOptionPane.CLOSED_OPTION);
		    return;
    	}
    	if(selectedCustomer==null)
    	{	
    		JOptionPane.showConfirmDialog(null, "您选择的车位为空,不用付钱","提示:", JOptionPane.CLOSED_OPTION);
		    return;
    	}
        CheckOutGUI checkout = new CheckOutGUI(selectedSpace,selectedCustomer,main);
    	checkout.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private JButton BSButton1;
    private JButton BSButton2;
    private JButton BSButton3;
    private JButton BSButton4;
    private JButton BSButton5;
    private JButton BSButton6;
    private JButton BSButton7;
    private JButton BSButton8;
    private JButton BSButton9;
    private JButton BSButton10;
    private JButton BDButton1;
    private JButton BDButton2;
    private JButton BDButton3;
    private JButton BDButton5;
    private JButton BDButton4;
    private JButton BDButton6;
    private JButton BDButton7;
    private JButton BDButton8;
    private JButton BDButton9;
    private JButton BDButton10;
    private JMenuItem menuItem_3;
    private JLabel label;
    private JLabel label_2;
    private JLabel label_3;
    private JLabel label_4;
    private JLabel label_5;
    private JLabel label_6;
    private JLabel label_7;
    private JLabel label_8;
    private JLabel label_9;
    private JLabel label_10;
    private JLabel label_11;
    private JLabel label_12;
    private JLabel label_13;
    private JLabel label_14;
    


	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		JButton jButton =( JButton)e.getSource();
		selectedButtonText=jButton.getText();
		selectedSpace = SpaceControl.getSpaceControl().getSpaceBySpaceID(selectedButtonText);
		if(selectedSpace.getSpaceState().equals("已占用"))
		{
			selectedCustomer = CustomerControl.getCustomerControl().getCustomerBySpaceID(selectedSpace);
		}
		else
		{ 
			selectedCustomer=null;
		}
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	
}
	
